"""
Shared state schema for the PR review graph.

THE STATE DESIGN PATTERN:
=========================
LangGraph uses a shared state object that flows through all nodes.
Each node reads from state and writes back to it.

This schema defines ALL data that moves through the graph:
- Input data (PR info, files)
- Tool outputs (language detection, static analysis, context search)
- Agent outputs (reviewer findings, judge scores)

State design principles:
1. Immutable types where possible (use dataclasses, not dicts)
2. Clear field names that indicate what data lives there
3. Optional fields for data that may not always be present
4. Type hints for IDE support and runtime validation
"""

from typing import TypedDict, List, Dict, Optional, Annotated
from dataclasses import dataclass, field
import operator

# Import our tool output types
from src.tools.diff_fetch import PRDiff, FileDiff
from src.language.detector import LanguageInfo
from src.static_analysis.base import Finding, AnalysisResult
from src.context_search.base import CodeReference


@dataclass
class ReviewerFinding:
    """
    A finding generated by the Reviewer agent (not from static analysis).

    These are ADDITIONAL issues the LLM found that tools missed:
    - Logic bugs
    - API misuse
    - Architecture issues
    - Performance problems
    - Security vulnerabilities the linters don't catch
    """
    file_path: str
    line: int
    severity: str  # "critical", "major", "minor"
    category: str  # "bug", "security", "performance", "style", "logic"
    title: str  # Short description
    description: str  # Detailed explanation
    suggestion: str  # How to fix it
    confidence: float  # 0.0 to 1.0 - how confident the agent is

    def to_dict(self):
        return {
            "file_path": self.file_path,
            "line": self.line,
            "severity": self.severity,
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "suggestion": self.suggestion,
            "confidence": self.confidence,
        }


class PRReviewState(TypedDict):
    """
    The shared state that flows through the entire graph.

    LangGraph passes this to every node. Nodes read what they need
    and write back their results.

    GRAPH FLOW:
    ===========
    1. fetch_diff_node: Writes pr_diff, repository, pr_number
    2. detect_language_node: Reads pr_diff, writes detected_languages
    3. run_static_analysis_node: Reads pr_diff + detected_languages, writes static_analysis_findings
    4. search_context_node: Reads pr_diff + detected_languages, writes context_references
    5. reviewer_agent_node: Reads EVERYTHING, writes reviewer_findings
    6. judge_agent_node (future): Reads reviewer_findings, writes filtered_findings
    """

    # ===== INPUT FIELDS (set at graph start) =====
    repository: str  # "owner/repo"
    pr_number: int
    github_token: Optional[str]

    # ===== DIFF FETCHING =====
    pr_diff: Optional[PRDiff]  # Complete diff from GitHub API

    # ===== LANGUAGE DETECTION =====
    detected_languages: List[LanguageInfo]  # Languages found in the diff
    primary_language: Optional[str]  # The most common language (for agent prompt)

    # ===== STATIC ANALYSIS =====
    # Map of language -> AnalysisResult summary (dict, not object - for serializability)
    static_analysis_results: Dict[str, dict]

    # Flattened list of ALL static analysis findings across all languages
    # This is what the Reviewer agent sees (language-agnostic)
    static_analysis_findings: Annotated[List[Finding], operator.add]

    # ===== CONTEXT SEARCH =====
    # Map of symbol -> list of references
    # Populated by searching for key symbols from the diff
    context_references: Dict[str, List[CodeReference]]

    # ===== REVIEWER AGENT OUTPUT =====
    # Findings generated by the LLM reviewer (beyond what static analysis caught)
    reviewer_findings: Annotated[List[ReviewerFinding], operator.add]

    # ===== JUDGE AGENT OUTPUT =====
    # Filtered findings after judge verification
    filtered_findings: Annotated[List[ReviewerFinding], operator.add]

    # Judge configuration
    judge_threshold: float  # Minimum score to pass (0.0-1.0), default 0.6

    # ===== POSTING CONFIGURATION =====
    auto_post_threshold: float  # Findings >= this score auto-post (default 0.8)
    manual_approval_threshold: float  # Findings >= this need approval (default 0.5)
    # Findings < manual_approval_threshold are discarded

    # ===== POSTING STATE =====
    pending_approval: List[ReviewerFinding]  # Findings awaiting manual approval
    approved_findings: List[ReviewerFinding]  # Findings approved for posting
    posted_findings: List[ReviewerFinding]  # Findings that were posted to GitHub

    # ===== METADATA =====
    errors: Annotated[List[str], operator.add]  # Error messages from any node
    node_outputs: Dict[str, dict]  # Metadata from each node (for debugging)


def create_initial_state(
    repository: str,
    pr_number: int,
    github_token: Optional[str] = None,
    judge_threshold: float = 0.6,
    auto_post_threshold: float = 0.8,
    manual_approval_threshold: float = 0.5
) -> PRReviewState:
    """
    Create the initial state for a PR review.

    This is what you pass to graph.invoke() to start the review.

    Args:
        repository: GitHub repo in "owner/repo" format
        pr_number: Pull request number
        github_token: GitHub token for API access
        judge_threshold: Minimum score for Judge to pass findings (0.0-1.0)
                        0.8 = strict, 0.6 = moderate (default), 0.4 = lenient
        auto_post_threshold: Findings with confidence >= this auto-post (default 0.8)
        manual_approval_threshold: Findings >= this but < auto_post need approval (default 0.5)
                                   Findings < this are discarded

    Example:
        >>> state = create_initial_state("facebook/react", 12345, "ghp_token123")
        >>> result = graph.invoke(state)
    """
    return PRReviewState(
        repository=repository,
        pr_number=pr_number,
        github_token=github_token,
        pr_diff=None,
        detected_languages=[],
        primary_language=None,
        static_analysis_results={},
        static_analysis_findings=[],
        context_references={},
        reviewer_findings=[],
        filtered_findings=[],
        judge_threshold=judge_threshold,
        auto_post_threshold=auto_post_threshold,
        manual_approval_threshold=manual_approval_threshold,
        pending_approval=[],
        approved_findings=[],
        posted_findings=[],
        errors=[],
        node_outputs={},
    )


# ===== REDUCER ANNOTATIONS EXPLAINED =====
#
# Notice the `Annotated[List[...], operator.add]` on some fields?
#
# This tells LangGraph HOW to merge updates when multiple nodes write to
# the same field. Without this, later writes would OVERWRITE earlier ones.
#
# With `operator.add`:
# - Node A writes: state["errors"] = ["error 1"]
# - Node B writes: state["errors"] = ["error 2"]
# - Final state: state["errors"] = ["error 1", "error 2"]  ← merged!
#
# This is CRITICAL for:
# - static_analysis_findings: Multiple analyzers append their findings
# - reviewer_findings: Reviewer appends its findings
# - errors: Any node can add error messages
#
# Without reducers, the last node to write would wipe out earlier results.
